# Generated by Django 4.1.2 on 2022-10-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fude_app', '0002_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
